# Setting up the environment

## IDE

Following the philosophy of having less distractions, you can install any of the following IDE's as per your choice. We will not be going through their setup.

1.  Visual Studio Code.
2.  Visual Studio Community.
3.  CLion.
4.  VIM.

## Get Initial Blockchain Data

Getting hands on initial bitcoin raw data without downloading whole blockchain is hard. Either download the whole data from bitcoin client or use the following github link for initial 1k data: [1k_initial.dat](https://github.com/nullicist-aakash/blockchain_cpp/blob/main/data/1k_initial.dat).

## Hex Viewer

First, we will create a simple hex viewer in `C++` which will let us view the byte contents in hexadecimal format. This is similar to `xxd` command in linux.

### C++ Code

We will take `str` as input for our starting address and `len` specifies how many bytes we want to display starting from address `str`. Here is the code for our hex viewer:
```{C++}
#define HEX( x, len ) std::setw(2 * len) << std::setfill('0') << std::hex << std::uppercase << (((1ll << (8 * len)) - 1) & (unsigned int)( x )) << std::dec

void hex_view(const char* str, const size_t len)
{
    for (int i = 0; i < ((int)len >> 4) + (len % 16 ? 1 : 0); ++i)
    {
        int start = i * 16;
        int end = std::min(i * 16 + 15, (int)len - 1);
        std::cout << "0x" << HEX(start, 4) << " |  ";
        for (int j = start; j <= end; ++j)
            std::cout << HEX(str[j], 1) << (j % 8 == 7 ? "  " : " ");

        for (int j = end; j < i * 16 + 15; ++j)
            std::cout << (j % 8 == 7 ? "    " : "   ");
        std::cout << "| ";
        for (int j = start; j <= end; ++j)
            std::cout << (std::isprint(str[j]) ? str[j] : '.');
        std::cout << '\n';
    }
}
```

### Working of `hex_view`
You can safely skip this portion as we will be using above code as black-box from now on and the internal working of it is irrelevant to our discussion.

Outer for loop takes care of how many lines to print. Inside the loop, we first initialise the `start` and `end` memory indices so that we don't print out-of-bound memory by mistake. Then, we print the offsets. After that, we use `HEX` macro defined above to print the memory characters in specified number of `bytes`. At the last, we print the characters in ASCII format. Here is the summary of functions used in above code:

1. `std::setw`: Present in `<iomanip>` header, specifies the width of output. Don't worry if you don't know about this. We will not use this again.
2. `std::setfill`: This is used to print the given character (`'0'` here) instead of spaces which were introduced by `setw`.
3. `std::hex`: This specifies that we want to print the integers in hexadecimal format. The default behaviors is `std::dec` which is used in last of this macro to reset the output manipulator.
4. `std::uppercase`: This specifies that we want to print everything in uppercase. This ensures that we will print integer $10$ as $0A$ instead of $0a$.
5. `std::isprint`: This will return `true` if the output character is a printable ASCII character. We simply print a dot `.` if this is not the case, otherwise the equivalent ASCII character.

We will be using `HEX` again and again to display our output, so it is necessary to get familiar with the syntax.

### Bitcoin Data
We will use the above `hex_view` function to see the contents of initial bitcoin data. First, we will read from `.dat` file using `fstream`. Then we will read the whole data inside character array and then, display the contents in hexadecimal format.

Here is the code to display the initial bitcoin data in hexadecimal:
```{C++}
#include <iostream>
#include <fstream>
#include <algorithm>
#include <string>
#define HEX( x, len ) std::setw(2 * len) << std::setfill('0') << std::hex << std::uppercase << (((1ll << (8 * len)) - 1) & (unsigned int)( x )) << std::dec

void hex_view(const char* str, const size_t len)
{
    for (int i = 0; i < ((int)len >> 4) + (len % 16 ? 1 : 0); ++i)
    {
        int start = i * 16;
        int end = std::min(i * 16 + 15, (int)len - 1);
        std::cout << "0x" << HEX(start, 4) << " |  ";
        for (int j = start; j <= end; ++j)
            std::cout << HEX(str[j], 1) << (j % 8 == 7 ? "  " : " ");

        for (int j = end; j < i * 16 + 15; ++j)
            std::cout << (j % 8 == 7 ? "    " : "   ");
        std::cout << "| ";
        for (int j = start; j <= end; ++j)
            std::cout << (std::isprint(str[j]) ? str[j] : '.');
        std::cout << '\n';
    }
}

// Returns the file contents as C++ string
std::string get_file_contents(const char *filename)
{
    std::ifstream in(filename, std::ios::in | std::ios::binary);
    if (!in)
    {
        std::cerr << "Error in opening file" << std::endl;
        throw errno;
    }

    std::string contents;

    // Allocate required memory in heap for string
    in.seekg(0, std::ios::end);
    contents.resize(in.tellg());

    // Copy contents from file to string
    in.seekg(0, std::ios::beg);
    in.read(&contents[0], (int)contents.size());

    // return the string
    return contents;
}

int main()
{
    const char* FILE_PATH = "<file_location_here>";
    auto contents = get_file_contents(FILE_PATH);
    hex_view(contents.c_str(), contents.size());
}
```

Understanding above code is very simple. In the function `get_file_contents`, we take the file path as input. If we are unable to open file in `binary` mode for reading, we simply exit. Otherwise, we copy the contents from whole file to string and then return it. Finally, we are printing the contents of file in hexadecimal format. 

Here is the output of running above code on initial $1k$ bitcoin data:
```{}
0x00000000 |  F9 BE B4 D9 1D 01 00 00  01 00 00 00 00 00 00 00  | ................
0x00000010 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000020 |  00 00 00 00 00 00 00 00  00 00 00 00 3B A3 ED FD  | ............;...
0x00000030 |  7A 7B 12 B2 7A C7 2C 3E  67 76 8F 61 7F C8 1B C3  | z{..z.,>gv.a....
0x00000040 |  88 8A 51 32 3A 9F B8 AA  4B 1E 5E 4A 29 AB 5F 49  | ..Q2:...K.^J)._I
0x00000050 |  FF FF 00 1D 1D AC 2B 7C  01 01 00 00 00 01 00 00  | ......+|........
0x00000060 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000070 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 FF FF  | ................
0x00000080 |  FF FF 4D 04 FF FF 00 1D  01 04 45 54 68 65 20 54  | ..M.......EThe T
0x00000090 |  69 6D 65 73 20 30 33 2F  4A 61 6E 2F 32 30 30 39  | imes 03/Jan/2009
0x000000A0 |  20 43 68 61 6E 63 65 6C  6C 6F 72 20 6F 6E 20 62  |  Chancellor on b
0x000000B0 |  72 69 6E 6B 20 6F 66 20  73 65 63 6F 6E 64 20 62  | rink of second b
0x000000C0 |  61 69 6C 6F 75 74 20 66  6F 72 20 62 61 6E 6B 73  | ailout for banks
0x000000D0 |  FF FF FF FF 01 00 F2 05  2A 01 00 00 00 43 41 04  | ........*....CA.
0x000000E0 |  67 8A FD B0 FE 55 48 27  19 67 F1 A6 71 30 B7 10  | g....UH'.g..q0..
0x000000F0 |  5C D6 A8 28 E0 39 09 A6  79 62 E0 EA 1F 61 DE B6  | \..(.9..yb...a..
0x00000100 |  49 F6 BC 3F 4C EF 38 C4  F3 55 04 E5 1E C1 12 DE  | I..?L.8..U......
0x00000110 |  5C 38 4D F7 BA 0B 8D 57  8A 4C 70 2B 6B F1 1D 5F  | \8M....W.Lp+k.._
0x00000120 |  AC 00 00 00 00 F9 BE B4  D9 D7 00 00 00 01 00 00  | ................
0x00000130 |  00 6F E2 8C 0A B6 F1 B3  72 C1 A6 A2 46 AE 63 F7  | .o......r...F.c.
0x00000140 |  4F 93 1E 83 65 E1 5A 08  9C 68 D6 19 00 00 00 00  | O...e.Z..h......
0x00000150 |  00 98 20 51 FD 1E 4B A7  44 BB BE 68 0E 1F EE 14  | .. Q..K.D..h....
0x00000160 |  67 7B A1 A3 C3 54 0B F7  B1 CD B6 06 E8 57 23 3E  | g{...T.......W#>
0x00000170 |  0E 61 BC 66 49 FF FF 00  1D 01 E3 62 99 01 01 00  | .a.fI......b....
0x00000180 |  00 00 01 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000190 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x000001A0 |  00 00 00 FF FF FF FF 07  04 FF FF 00 1D 01 04 FF  | ................
0x000001B0 |  FF FF FF 01 00 F2 05 2A  01 00 00 00 43 41 04 96  | .......*....CA..
0x000001C0 |  B5 38 E8 53 51 9C 72 6A  2C 91 E6 1E C1 16 00 AE  | .8.SQ.rj,.......
0x000001D0 |  13 90 81 3A 62 7C 66 FB  8B E7 94 7B E6 3C 52 DA  | ...:b|f....{.<R.
0x000001E0 |  75 89 37 95 15 D4 E0 A6  04 F8 14 17 81 E6 22 94  | u.7...........".
0x000001F0 |  72 11 66 BF 62 1E 73 A8  2C BF 23 42 C8 58 EE AC  | r.f.b.s.,.#B.X..
0x00000200 |  00 00 00 00 F9 BE B4 D9  D7 00 00 00 01 00 00 00  | ................
0x00000210 |  48 60 EB 18 BF 1B 16 20  E3 7E 94 90 FC 8A 42 75  | H`..... .~....Bu
0x00000220 |  14 41 6F D7 51 59 AB 86  68 8E 9A 83 00 00 00 00  | .Ao.QY..h.......
0x00000230 |  D5 FD CC 54 1E 25 DE 1C  7A 5A DD ED F2 48 58 B8  | ...T.%..zZ...HX.
0x00000240 |  BB 66 5C 9F 36 EF 74 4E  E4 2C 31 60 22 C9 0F 9B  | .f\.6.tN.,1`"...
0x00000250 |  B0 BC 66 49 FF FF 00 1D  08 D2 BD 61 01 01 00 00  | ..fI.......a....
0x00000260 |  00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000270 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000280 |  00 00 FF FF FF FF 07 04  FF FF 00 1D 01 0B FF FF  | ................
0x00000290 |  FF FF 01 00 F2 05 2A 01  00 00 00 43 41 04 72 11  | ......*....CA.r.
0x000002A0 |  A8 24 F5 5B 50 52 28 E4  C3 D5 19 4C 1F CF AA 15  | .$.[PR(....L....
0x000002B0 |  A4 56 AB DF 37 F9 B9 D9  7A 40 40 AF C0 73 DE E6  | .V..7...z@@..s..
0x000002C0 |  C8 90 64 98 4F 03 38 52  37 D9 21 67 C1 3E 23 64  | ..d.O.8R7.!g.>#d
0x000002D0 |  46 B4 17 AB 79 A0 FC AE  41 2A E3 31 6B 77 AC 00  | F...y...A*.1kw..
0x000002E0 |  00 00 00 F9 BE B4 D9 D7  00 00 00 01 00 00 00 BD  | ................
0x000002F0 |  DD 99 CC FD A3 9D A1 B1  08 CE 1A 5D 70 03 8D 0A  | ...........]p...
0x00000300 |  96 7B AC B6 8B 6B 63 06  5F 62 6A 00 00 00 00 44  | .{...kc._bj....D
0x00000310 |  F6 72 22 60 90 D8 5D B9  A9 F2 FB FE 5F 0F 96 09  | .r"`..]....._...
0x00000320 |  B3 87 AF 7B E5 B7 FB B7  A1 76 7C 83 1C 9E 99 5D  | ...{.....v|....]
0x00000330 |  BE 66 49 FF FF 00 1D 05  E0 ED 6D 01 01 00 00 00  | .fI.......m.....
0x00000340 |  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000350 |  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  | ................
0x00000360 |  00 FF FF FF FF 07 04 FF  FF 00 1D 01 0E FF FF FF  | ................
0x00000370 |  FF 01 00 F2 05 2A 01 00  00 00 43 41 04 94 B9 D3  | .....*....CA....
0x00000380 |  E7 6C 5B 16 29 EC F9 7F  FF 95 D7 A4 BB DA C8 7C  | .l[.)..........|
0x00000390 |  C2 60 99 AD A2 80 66 C6  FF 1E B9 19 12 23 CD 89  | .`....f......#..
0x000003A0 |  71 94 A0 8D 0C 27 26 C5  74 7F 1D B4 9E 8C F9 0E  | q....'&.t.......
0x000003B0 |  75 DC 3E 35 50 AE 9B 30  08 6F 3C D5 AA AC 00 00  | u.>5P..0.o<.....
0x000003C0 |  00 00 F9 BE B4 D9 D7 00  00 00 01 00 00 00 49 44  | ..............ID
0x000003D0 |  46 95 62 AE 1C 2C 74 D9  A5 35 E0 0B 6F 3E 40 FF  | F.b..,t..5..o>@.
0x000003E0 |  BA D4 F2 FD A3 89 55 01                           | ......U.

```

I don't know about you but I see a lot of gibberish and between that gibberish, something in english: `The Times 03/Jan/2009...'. This message was left by __Satoshi Nakamoto__, the developer of bitcoin, in the __Genesis block__. We are starting somewhere. In order to extract that text and read it via code and understand what is other gibberish, we need to go to next lesson.

## Disclaimer {-}
`C++` code used above may seem intimidating. Don't worry. I copied the code from internet and applied what I thought was required to make my `hex_viewer`. There may exist some easier implementation but we are focussing on structure of bitcoin here, not on how I wrote the `hex_viewer`. This is just used for debugging purposes and cross-check that we are going in right direction. You can safely assume that above code is correct and we don't have to see inside them at all in future lessons.
